### ISSUE TITLE
小三角的制作方法

### ISSUE THREAD

**Issue by sunjunjiegithub** [sunjunjiegithub/learn_front_end_basic#62]
经常会用到的气泡框需要一个小三角, 可以用以下css实现
```css
.angle {
  width:0;
  height:0;
  border:8px solid;
  border-color:black transparent transparent transparent;
}
```
